services:
  skysafe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skysafe
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MARIADB_URI=${MARIADB_URI}
      - MONGODB_URI=${MONGODB_URI}
    restart: unless-stopped
    depends_on:
      - mariadb

  mariadb:
    image: docker.io/library/mariadb:10.11
    container_name: skysafe_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ilyushin76
      MARIADB_DATABASE: skysafe
      MARIADB_USER: skysafe_user
      MARIADB_PASSWORD: ilyushin76
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
